# Generated by Django 4.2.1 on 2023-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='add_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
