# Generated by Django 4.2.1 on 2023-05-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaladded',
            name='raw_data',
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='add_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='coord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
