# Generated by Django 4.2.1 on 2023-05-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_remove_perevaladded_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.images'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.perevaladded'),
        ),
    ]
