# Generated by Django 4.2.1 on 2023-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_perevalimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=10),
        ),
    ]
