# Generated by Django 4.2.1 on 2023-05-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_perevaladded_coord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
