# Generated by Django 4.2.1 on 2023-05-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_perevaladded_coord_alter_perevalimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.perevaladded'),
        ),
        migrations.DeleteModel(
            name='PerevalImages',
        ),
    ]
