# Generated by Django 4.2.1 on 2023-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0009_alter_images_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
