# Generated by Django 4.2.1 on 2023-05-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0013_alter_image_pereval'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
